USE research_mysql2;

CREATE TABLE IF NOT EXISTS journal_rankings (
    journal_ranking_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sjr_rank INT,
    title VARCHAR(512) NOT NULL,
    oa BOOLEAN,
    country VARCHAR(128),
    sjr_index DECIMAL(10,3),
    citescore DECIMAL(10,2),
    h_index INT,
    best_quartile VARCHAR(10),
    best_categories JSON,
    best_subject_area VARCHAR(255),
    best_subject_rank VARCHAR(50),
    total_docs INT,
    total_docs_3y INT,
    total_refs INT,
    total_cites_3y INT,
    citable_docs_3y INT,
    cites_per_doc_2y DECIMAL(10,3),
    refs_per_doc DECIMAL(10,3),
    publisher VARCHAR(255),
    core_collection VARCHAR(255),
    coverage VARCHAR(100),
    active BOOLEAN,
    in_press BOOLEAN,
    iso_language_code VARCHAR(10),
    asjc_codes TEXT,
    source_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_journal_rankings_title (title),
    INDEX idx_journal_rank (sjr_rank),
    INDEX idx_journal_country (country),
    INDEX idx_journal_quartile (best_quartile),
    INDEX idx_journal_sjr (sjr_index)
);
